name: Build ROM

on:
  workflow_dispatch:
    inputs:
      cleanstrategy:
        description: 'Select Clean strategy'
        required: true
        default: 'installclean'
        type: choice
        options:
          - nope
          - installclean
          - clobber
          
      sync:
        description: 'Select if sync'
        required: true
        default: 'false'
        type: boolean

env:
  RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_CHAT: ${{ secrets.TG_CHAT }}
  SYNC_FLAG: ${{ github.event.inputs.sync }}
  CLEAN: ${{ github.event.inputs.cleanstrategy }}

# queue up builds to prevent failures on progress of other builds
concurrency:
  group: building_rom
  cancel-in-progress: false

jobs:
  build:
    timeout-minutes: 2400
    runs-on: self-hosted
    environment:
      name: Builder

    steps:
      - name: Checkout
        run: |
          cd ~/miku/
          rm -rf __rom-build_scripts__
          git_branch=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          echo "Branch: $git_branch"
          git clone ${{ github.server_url }}/${{ github.repository }} __rom-build_scripts__ -b $git_branch --depth 1 --single-branch

      - name: Build
        run: |
          cd ~/miku/
          source __rom-build_scripts__/._env
          required_files=( _utils.sh _build.sh ._env vendor-setup-miku.sh $REPOS_JSON )
          rm -rf "${required_files[@]}"
          for file in "${required_files[@]}"; do
            if [ ! -f "__rom-build_scripts__/$file" ]; then
              echo "File $file not found!"
              exit 1
            fi
            cp -r "__rom-build_scripts__/$file" .
          done
          chmod +x _build.sh
          ./_build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Logs
          path: '*.log'
